### ISSUE TITLE
TypeError: Cannot read property 'text' of undefined at renderFullPage

### ISSUE THREAD

**Issue by ryantbrown** [PaymentRails/php-sdk#2]
I don't see a repo for the JS Widget so I am posting this here in hopes of getting some help.
I am generating the `iframe` url and the following is what I get:

`https://widget.paymentrails.com/?email=ryan.brown.916@gmail.com&amp;refid=f5e4b7b4-8ca2-49e9-a47d-73d854c99565&ts=1523926618&key=ASVAnQSK795JURZ3UYGHA5DX&sign=1c7816947a5ea12ded68c672b0559c64d50a6749859744a40a4780d8d3ebeb83`

When I load this in the browser or via the `iframe` `src` I get the same error, here is the full trace:

```
TypeError: Cannot read property 'text' of undefined
    at renderFullPage (/opt/app/server/index.js:21:29)
    at /opt/app/server/index.js:71:12
    at Layer.handle [as handle_request] (/opt/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/app/node_modules/express/lib/router/route.js:137:13)
    at middlewareFunction (/opt/app/server/middleware/domainRestriction.js:14:3)
    at Layer.handle [as handle_request] (/opt/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/app/node_modules/express/lib/router/route.js:137:13)
    at _callee$ (/opt/app/server/middleware/session.js:45:3)
    at tryCatch (/opt/app/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/opt/app/node_modules/regenerator-runtime/runtime.js:303:22)
```

I am in "Test" mode and have not completed the activation process, could either of these things be the cause?

**Comment by koblas** [comment]
There is a problem with the authentication of your widget call, which is triggering an error in the HTML generator.  We will get back to you via direct communications to figure out the specifics of the issue and also fix the code on our side.
